### ISSUE TITLE
node parsing failed

### ISSUE THREAD

**Issue by Droog159** [evolutionleo/GM-Online-Framework#2]
gms sned:Encoding data: { x : 766, y : 261, cmd : 8, mid : "ujQnPFJP1wa" }
node parsing failed:
\node_modules\@msgpack\msgpack\dist\Decoder.js:85
            throw this.createExtraByteError(this.pos);
            ^

RangeError: Extra 16 of 30 byte(s) found at buffer[14]
    at Decoder.createExtraByteError (D:\typescript\js_server - 副本 (2)\node_modules\@msgpack\msgpack\dist\Decoder.js:78:16)
    at Decoder.decode (D:\typescript\js_server \node_modules\@msgpack\msgpack\dist\Decoder.js:85:24)
    at decode (D:\typescript\js_server \node_modules\@msgpack\msgpack\dist\decode.js:13:20)
    at Function.parse (D:\typescript\js_server\packet.js:25:20)
    at Socket.<anonymous> (D:\typescript\js_server\main.js:43:25)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by evolutionleo** [comment]
This appears to be an error on the SNAP's side
I'll update the imports as soon as Juju fixes the pug

**Comment by Droog159** [comment]
TCP doesn't seem to like many and small packages. If there are many packages, the node server seems to be unable to accept them.

**Comment by evolutionleo** [comment]
Update: this was actually fixed completely in the [latest release](https://github.com/evolutionleo/GM-Online-Framework/releases/latest) (v3.2), this was in fact a problem in TCP, but I made a work-around that should fix it! :D
